### PR TITLE
Cloud Storage objects may lack Content-Type

### LINKED ISSUE #9: Undefined index: contentType in GoogleCloudStorageAdapter.php line 473
We get the following error when calling `Storage::disk('gcs')->listContents('ftp/pyramid')`:

```
In GoogleCloudStorageAdapter.php line 473:

  [ErrorException]
  Undefined index: contentType


Exception trace:
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at /var/www/aroma-pos/vendor/cedricziel/flysystem-gcs/src/GoogleCloudStorageAdapter.php:473
 CedricZiel\FlysystemGcs\GoogleCloudStorageAdapter->convertObjectInfo() at /var/www/aroma-pos/vendor/cedricziel/flysystem-gcs/src/GoogleCloudStorageAdapter.php:334
 CedricZiel\FlysystemGcs\GoogleCloudStorageAdapter->listContents() at /var/www/aroma-pos/vendor/league/flysystem/src/Filesystem.php:271
 League\Flysystem\Filesystem->listContents() at n/a:n/a
 call_user_func_array() at /var/www/aroma-pos/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php:682
 Illuminate\Filesystem\FilesystemAdapter->__call() at /var/www/aroma-pos/app/Console/Commands/ImportFromPyramid.php:102
 App\Console\Commands\ImportFromPyramid->initFileList() at /var/www/aroma-pos/app/Console/Commands/ImportFromPyramid.php:84
```

skarmdump 2018-01-26t09 54 16

### PR DESCRIPTION
**Pull request by emilv**
Fix #9

### CODE REVIEW

**Review by cedricziel — APPROVED** [review]

**Comment by cedricziel** [comment]
Thanks a bunch! This library needs a little love, so every contribution is highly appreciated!

**Comment by emilv** [comment]
No problem! We use it in production so of course we spend time fixing important bugs. Your library is used by https://github.com/websightgmbh/l5-google-cloud-storage which is the only one I found that works with Laravel 5.5.

**Comment by emilv** [comment]
I just realized that is your library too! :D Thanks for your work!

**Comment by cedricziel** [comment]
Hehe, yes ;)

Glad it helps you! Please open further issues if you find something!

**Pull request merged**
